#!/bin/bash

function _aws_env() {
  profile="${AWS_PROFILE}"
  [[ $# -ge 1 ]] && profile="${1}"
  [[ -z "${profile}" ]] && echo "AWS cli unconfigured - didn't get a profile name as argument or as env \$AWS_PROFILE" && return
  if [[ $# -le 0 ]] && command -v fzf
    then
      profiles="$(_aws_list_profiles | fzf --prompt "profiles: " -m | tr -d '[],')"
      _aws_unset
      echo "Loading AWS profile $profiles"
      export AWS_PROFILE=$profiles
  else
    _aws_unset
    echo "Loading AWS profile $profile"
    export AWS_PROFILE=$profile
  fi
}

function _aws_unset() {
  unset AWS_PROFILE
  unset AWS_ACCESS_KEY_ID
  unset AWS_SECRET_ACCESS_KEY
}

function _aws_list_profiles() {
  credentialFile="${AWS_CREDENTIAL_FILE:-'~/.aws/credentials'}"

  while read line; do
      if [[ $line == "["* ]]
        then 
          echo "$line" | sed 's/profile //g' # In case you need this to work with the ~/.aws/config and SSO 
      fi
  done < $credentialFile;
};

alias aws-switch="_aws_env"
alias aws-unset="_aws_unset"
alias aws-list="_aws_list_profiles"
alias aws-who="aws configure list"

aws-switch
